Add ban moderation command
Skurczybyki/bot pull request #16
Opened 2023-08-12 09:01 UTC by pawelek3113

2023-08-12 10:13 UTC, DownDev requested changes

2023-08-12 10:13 UTC, DownDev commented on src/ext/moderation.py
> +    @slash_command(description="Ban user", default_member_permissions=Permissions(8))
```suggestion
    @slash_command(description="Ban user", default_member_permissions=Permissions(administrator=True))
```

2023-08-12 10:13 UTC, DownDev commented on src/ext/moderation.py
> +            reason = "No reason given"
Domyslna wartosc w SlashOption

2023-08-12 10:13 UTC, DownDev commented on src/ext/moderation.py
> +            description="Clear user's messages", choices=["True", "False"], default=False, required=False
czemu choices sa jako string

2023-08-12 19:23 UTC, pawelek3113 commented on src/ext/moderation.py
> +            description="Clear user's messages", choices=["True", "False"], default=False, required=False
@DownDev choices: Dict[str, str | int | float] | Iterable[str | int | float] | None

2023-08-12 21:18 UTC, DownDev requested changes

2023-08-12 21:18 UTC, DownDev commented on src/ext/moderation.py
> +                await member.ban(reason=reason, delete_message_seconds=0)
0 jest domyslnie w `delete_message_seconds`

2023-08-12 21:18 UTC, DownDev commented on src/ext/moderation.py
>                  delete_message_seconds = 604800  # week
Po co robic zmienna?

2023-08-13 09:52 UTC, DownDev requested changes

2023-08-13 09:52 UTC, DownDev commented on src/ext/moderation.py
> +                await interaction.send(f"{interaction.user.mention} banned {user.display_name}! Reason: {reason}")
Powtarzanie kodu linia 31 i 34

2023-08-13 09:52 UTC, DownDev commented on src/ext/moderation.py
> +            choices=["Yes", "No"],
```suggestion
            choices={"Yes": True, "No": False},
```

2023-08-13 09:52 UTC, DownDev commented on src/ext/moderation.py
> +            if clear_messages == "No":
update tego zeby działał z wartoscia bool

2023-08-13 09:52 UTC, DownDev commented on src/ext/moderation.py
> +from nextcord import Forbidden, HTTPException, Interaction, Member, Permissions, SlashOption, User, slash_command
po co import Member

2023-08-13 10:39 UTC, DownDev commented on src/ext/moderation.py
> +    @slash_command(description="Ban user", default_member_permissions=Permissions(administrator=True))
make command guild only
https://docs.nextcord.dev/en/stable/ext/application_checks/index.html#nextcord.ext.application_checks.guild_only

2023-08-13 11:58 UTC, DownDev requested changes

2023-08-13 11:58 UTC, DownDev commented on src/ext/moderation.py
> +            if clear_messages == False:
if not ...:

2023-08-13 11:58 UTC, DownDev commented on src/ext/moderation.py
>      @slash_command(description="Ban user", default_member_permissions=Permissions(administrator=True))
czm administrator, a nie ban_members

2023-08-13 12:49 UTC, DownDev requested changes

2023-08-13 12:49 UTC, DownDev commented on src/ext/moderation.py
> +                await interaction.send(f"{interaction.user.mention}, you can't ban yourself!", ephemeral=True)
skoro interaction.user == user to wystarczy 
```suggestion
            if interaction.user == user:
                await interaction.send(f"{user.mention}, you can't ban yourself!", ephemeral=True)
```

2023-08-13 12:49 UTC, DownDev commented on src/ext/moderation.py
> +                await interaction.send(f"{interaction.user.mention} banned {user.display_name}! Reason: {reason}")
uzywaj guard clauses

2023-08-13 17:57 UTC, DownDev requested changes

2023-08-13 17:57 UTC, DownDev commented on src/ext/moderation.py
> +            if user == None:
is None

2023-08-13 18:35 UTC, DownDev commented on src/ext/moderation.py
> +from datetime import timedelta
?

2023-08-13 19:54 UTC, DownDev approved these changes

2023-08-13 19:55 UTC, merged